import { spawnSync } from "node:child_process"
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync
} from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { describe, expect, it } from "vitest"

const repository = resolve(import.meta.dirname, "..")
const fixture = join(repository, "examples", "parity", "filesystem.air")

const run = (
  args: ReadonlyArray<string>,
  home: string
) =>
  spawnSync("bun", ["src/cli.ts", ...args], {
    cwd: repository,
    env: { ...process.env, AIRLOCK_HOME: home },
    encoding: "utf8",
    timeout: 30_000
  })

describe("shell parity — native filesystem actions", () => {
  it("performs a common inspect/read/search/edit/copy/move/remove workflow through ProgramExecution", () => {
    const root = mkdtempSync(join(tmpdir(), "airlock-parity-files-"))
    const workspace = join(root, "workspace")
    const home = join(root, "home")
    mkdirSync(workspace)
    writeFileSync(join(workspace, "input.txt"), "source bytes\n")
    writeFileSync(join(workspace, "ignored.md"), "not a text match\n")

    const executed = run([
      "run",
      fixture,
      "--workspace",
      workspace
    ], home)

    expect(executed.status, executed.stderr).toBe(0)
    expect(existsSync(join(workspace, "input.txt"))).toBe(false)
    expect(readFileSync(join(workspace, "generated", "deep", "generated.txt"), "utf8"))
      .toBe("generated bytes\n")
    expect(existsSync(join(workspace, "generated", "deep", "copied.txt"))).toBe(false)
    expect(readFileSync(join(workspace, "generated", "final.txt"), "utf8"))
      .toBe("source bytes\n")

    const report = JSON.parse(executed.stdout) as {
      readonly result: {
        readonly result: {
          readonly inspected: { readonly kind: string; readonly bytes: number }
          readonly observed: string
          readonly metadata: { readonly kind: string; readonly bytes: number }
          readonly entries: ReadonlyArray<{ readonly name: string }>
          readonly matches: ReadonlyArray<string>
          readonly directories: { readonly state: string; readonly act_ids: ReadonlyArray<string> }
          readonly written: { readonly state: string }
          readonly copied: { readonly state: string }
          readonly moved: { readonly state: string }
          readonly removed: { readonly state: string }
        }
        readonly plans: ReadonlyArray<{
          readonly nodes: ReadonlyArray<{ readonly kind: string }>
        }>
      }
    }

    expect(report.result.result).toMatchObject({
      inspected: { kind: "file", bytes: 13 },
      observed: "source bytes\n",
      metadata: { kind: "file", bytes: 13 },
      entries: [{ name: "ignored.md" }, { name: "input.txt" }],
      directories: { state: "applied" },
      written: { state: "applied" },
      copied: { state: "applied" },
      moved: { state: "applied" },
      removed: { state: "applied" }
    })
    expect(report.result.result.matches).toEqual([
      expect.stringMatching(/\/workspace\/input\.txt$/)
    ])
    expect(report.result.result.directories.act_ids).toHaveLength(2)
    expect(report.result.plans).toHaveLength(10)
    expect(report.result.plans.flatMap(({ nodes }) => nodes.map(({ kind }) => kind)))
      .toEqual([
        "Capture",
        "Capture",
        "Capture",
        "Capture",
        "Capture",
        "Apply",
        "Apply",
        "Apply",
        "Apply",
        "Apply"
      ])

    const held = run(["held"], home)
    expect(held.status, held.stderr).toBe(0)
    const recoverable = JSON.parse(held.stdout) as ReadonlyArray<{
      readonly target: string
      readonly status: string
    }>
    expect(recoverable.length).toBeGreaterThanOrEqual(6)
    expect(recoverable.every(({ status }) => status === "held")).toBe(true)
    expect(recoverable.some(
      ({ target }) => target.endsWith("/workspace/input.txt")
    )).toBe(true)
  })
})
