#!/usr/bin/env python3
"""Generate candidate data, never production changes or an apply-time command."""
import json
import sys
from pathlib import Path

candidate = Path(sys.argv[1])
# Exclusive creation refuses to overwrite a previously generated candidate.
with (candidate / "config.json").open("x") as config:
    json.dump({"message": "reviewed candidate", "workers": 2}, config, indent=2)
    config.write("\n")
with (candidate / "README.txt").open("x") as readme:
    readme.write("Generated by Python before staging. Apply runs no command.\n")
